app:
  port: 3000
  log_level: info
  crontime: "*/1 * * * *"

uptimerobot:
  api_key: fake_api_key
  pattern:
  statuses: "2-9"

website:
  title: "服务状态"
  avatar: ""
  rtl: false
  copyright: "楠格"
  home:
    label: "主页"
    href: "/"
  github:
    href: "https://github.com/xOS"
  footer:
    title: ""
    description: "由 UptimeRobot 数据驱动，自动缓存并动态更新。"
    owner: ""
    owner_url: "https://www.nange.cn"
  links:
    - name: 主页
      href: http://about.nange.cn
    - name: 楠格
      href: http://www.nange.cn
    - name: 探针
      href: http://server.nange.cn
    - name: GitHub
      href: http://github.com/xOS
